"""first migration

Revision ID: 6df66e9e3021
Revises: 
Create Date: 2024-01-15 19:35:34.875164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6df66e9e3021"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.Enum("prepared", "connected", name="clusterstatusenum"), nullable=True),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_email", sa.String(), nullable=True),
        sa.Column("creation_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("provider", sa.Enum("aws", "on_prem", name="clusterproviderenum"), nullable=True),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "storage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fs_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("source", sa.Enum("vantage", "imported", name="storagesourceenum"), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("aws_arn", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", "fs_id"),
        sa.UniqueConstraint("fs_id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "mount_point",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cluster_name", sa.String(), nullable=False),
        sa.Column("storage_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("mount_point", sa.String(), server_default="/nfs", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("mounting", "mounted", "deleting", "error", name="mountpointstatusenum"),
            server_default="mounting",
            nullable=True,
        ),
        sa.Column("error", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_name"],
            ["cluster.name"],
        ),
        sa.ForeignKeyConstraint(
            ["storage_id"],
            ["storage.id"],
        ),
        sa.PrimaryKeyConstraint("id", "cluster_name", "storage_id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mount_point")
    op.drop_table("storage")
    op.drop_table("cluster")
    # ### end Alembic commands ###
