"""create relationship between cloud_account table and cluster table

Revision ID: dd48e27efb1d
Revises: 99256d93e254
Create Date: 2024-02-06 16:20:31.835960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd48e27efb1d"
down_revision = "99256d93e254"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("cloud_account_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_cluster_cloud_account_id_cloud_account",
        "cluster",
        "cloud_account",
        ["cloud_account_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_cluster_cloud_account_id_cloud_account", "cluster", type_="foreignkey")
    op.drop_column("cluster", "cloud_account_id")
    # ### end Alembic commands ###
