"""Core module for storing CloudFormation related constants."""

"""Dict to map the AMIs IDs in different regions

This list was generated by the following snippet (it must run as is):

\"\"\"Prints the AMI IDs for the head and compute nodes of the Slurm cluster.\"\"\"
from pprint import pprint as print

import boto3
from mypy_boto3_imagebuilder.client import ImagebuilderClient
from mypy_boto3_imagebuilder.type_defs import AmiTypeDef

AMI_MAPPER: dict[str, dict[str, str]] = {
    "head": {},
    "compute": {},
}

ib: ImagebuilderClient = boto3.client("imagebuilder")

def list_output_resources_from_image(image_name: str) -> list[AmiTypeDef]:
    \"\"\"List the AMIs resources from an image pipeline by name.\"\"\"
    images = ib.list_images(
        owner="Self",
        filters=[
            {"name": "name", "values": [image_name]},
        ],
        byName=True
    )

    image_version = images["imageVersionList"][0]

    image = ib.get_image(
        imageBuildVersionArn=image_version["arn"]
    )

    image_output_resources = image["image"]["outputResources"]["amis"]

    return image_output_resources

head_node_images = list_output_resources_from_image("Ubuntu - Slurm Head Node")
compute_node_images = list_output_resources_from_image("Ubuntu - Slurm Compute Node")

for head_node_ami, compute_node_ami in zip(head_node_images, compute_node_images):
    AMI_MAPPER["head"][head_node_ami["region"]] = head_node_ami["image"]
    AMI_MAPPER["compute"][compute_node_ami["region"]] = compute_node_ami["image"]

print(AMI_MAPPER)
"""
AMI_MAPPER = {
    # ARN: arn:aws:imagebuilder:us-west-2:266735843730:image/ubuntu---slurm-compute-node/2.0.5/1
    "compute": {
        "af-south-1": "ami-05e85d3f27f30a736",
        "ap-east-1": "ami-05f1a77c79d18f6f5",
        "ap-northeast-1": "ami-0ef576e78a1c2641a",
        "ap-northeast-2": "ami-08b44988cb14b5b2a",
        "ap-northeast-3": "ami-06e82b7782a7c5f0c",
        "ap-south-1": "ami-08352542e7c92fa25",
        "ap-south-2": "ami-0fac989719e1d535f",
        "ap-southeast-1": "ami-0d2691d60646696fe",
        "ap-southeast-2": "ami-0b259fb5fddf50c0b",
        "ap-southeast-3": "ami-08450a8d1b5897790",
        "ap-southeast-4": "ami-0663e8cce2002fd17",
        "ap-southeast-5": "ami-0659fa0db410649fc",
        "ap-southeast-7": "ami-067bbe4faa6c2832e",
        "ca-central-1": "ami-0714c1abed1e23640",
        "ca-west-1": "ami-0cd43ed61422f0417",
        "eu-central-1": "ami-05b33a35cad4bf0b0",
        "eu-central-2": "ami-099ea9f68a6dc843d",
        "eu-north-1": "ami-027fc1b99899f1357",
        "eu-south-1": "ami-050251efe713c7696",
        "eu-south-2": "ami-0bf63b4087c94cf6a",
        "eu-west-1": "ami-003d05298c50aec42",
        "eu-west-2": "ami-04c83a688108279f1",
        "eu-west-3": "ami-0677739e4558be65b",
        "il-central-1": "ami-0a17c144a9eaa18b5",
        "me-central-1": "ami-0dd65423814b56408",
        "me-south-1": "ami-0d00cca6df2c56a30",
        "mx-central-1": "ami-083c258f6c6cc151a",
        "sa-east-1": "ami-054386ff5b99e2d00",
        "us-east-1": "ami-08949475170817481",
        "us-east-2": "ami-04513bb967eb7f76e",
        "us-west-1": "ami-0171f43dcf8163d8a",
        "us-west-2": "ami-05edc3d01d8266e68",
    },
    # arn:aws:imagebuilder:us-west-2:266735843730:image/ubuntu---slurm-head-node/2.0.5/1
    "head": {
        "af-south-1": "ami-09a28eb8052cce8bf",
        "ap-east-1": "ami-042c2d59d317752f3",
        "ap-northeast-1": "ami-068845a1734d462b9",
        "ap-northeast-2": "ami-006649f9900c5cc5c",
        "ap-northeast-3": "ami-03eab31576b53b9ed",
        "ap-south-1": "ami-01a0eced486a52892",
        "ap-south-2": "ami-003bb51d95ead9ca7",
        "ap-southeast-1": "ami-0b00b18e8b9c49aa1",
        "ap-southeast-2": "ami-08fff735ffcbe6a6d",
        "ap-southeast-3": "ami-0e3f6719f7253f301",
        "ap-southeast-4": "ami-01affc050231d727c",
        "ap-southeast-5": "ami-0eb5866904c027735",
        "ap-southeast-7": "ami-068bc4aa996560e73",
        "ca-central-1": "ami-0754f58d1d6cfcdc9",
        "ca-west-1": "ami-094cba580fa1ec900",
        "eu-central-1": "ami-021457647f758a537",
        "eu-central-2": "ami-06383279ce3b05703",
        "eu-north-1": "ami-0606ff0af4de5b5a7",
        "eu-south-1": "ami-0e15cd745ade97bdd",
        "eu-south-2": "ami-03ac9962065f03176",
        "eu-west-1": "ami-02c14c2bf3aee7e09",
        "eu-west-2": "ami-07a554dd355f13a83",
        "eu-west-3": "ami-01b1ce23fb7150454",
        "il-central-1": "ami-08631e9f5f109f00c",
        "me-central-1": "ami-009ea2ef8ea245476",
        "me-south-1": "ami-0aad44795ce3519b4",
        "mx-central-1": "ami-0ed803c774c79f4dd",
        "sa-east-1": "ami-04b302d458fcb5f39",
        "us-east-1": "ami-01a66443930f7f94b",
        "us-east-2": "ami-0f650f7e6111900f6",
        "us-west-1": "ami-0b27201f6cf89d5d5",
        "us-west-2": "ami-01bf2ca9c8d13c9a6",
    },
}

"""Dict to map the availability zones per region"""
AVZ_MAPPER = {
    "af-south-1": {"public": "af-south-1a", "private": "af-south-1b"},
    "ap-east-1": {"public": "ap-east-1a", "private": "ap-east-1b"},
    "ap-northeast-1": {"public": "ap-northeast-1a", "private": "ap-northeast-1b"},
    "ap-northeast-2": {"public": "ap-northeast-2a", "private": "ap-northeast-2b"},
    "ap-northeast-3": {"public": "ap-northeast-3a", "private": "ap-northeast-3b"},
    "ap-south-1": {"public": "ap-south-1a", "private": "ap-south-1b"},
    "ap-south-2": {"public": "ap-south-2a", "private": "ap-south-2b"},
    "ap-southeast-1": {"public": "ap-southeast-1a", "private": "ap-southeast-1b"},
    "ap-southeast-2": {"public": "ap-southeast-2a", "private": "ap-southeast-2b"},
    "ap-southeast-3": {"public": "ap-southeast-3a", "private": "ap-southeast-3b"},
    "ap-southeast-4": {"public": "ap-southeast-4a", "private": "ap-southeast-4b"},
    "ap-southeast-5": {"public": "ap-southeast-5a", "private": "ap-southeast-5b"},
    "ca-central-1": {"public": "ca-central-1a", "private": "ca-central-1b"},
    "ca-west-1": {"public": "ca-west-1a", "private": "ca-west-1b"},
    "eu-central-1": {"public": "eu-central-1a", "private": "eu-central-1b"},
    "eu-central-2": {"public": "eu-central-2a", "private": "eu-central-2b"},
    "eu-north-1": {"public": "eu-north-1a", "private": "eu-north-1b"},
    "eu-south-1": {"public": "eu-south-1a", "private": "eu-south-1b"},
    "eu-south-2": {"public": "eu-south-2a", "private": "eu-south-2b"},
    "eu-west-1": {"public": "eu-west-1a", "private": "eu-west-1b"},
    "eu-west-2": {"public": "eu-west-2a", "private": "eu-west-2b"},
    "eu-west-3": {"public": "eu-west-3a", "private": "eu-west-3b"},
    "il-central-1": {"public": "il-central-1a", "private": "il-central-1b"},
    "me-central-1": {"public": "me-central-1a", "private": "me-central-1b"},
    "me-south-1": {"public": "me-south-1a", "private": "me-south-1b"},
    "sa-east-1": {"public": "sa-east-1a", "private": "sa-east-1b"},
    "us-east-1": {"public": "us-east-1a", "private": "us-east-1b"},
    "us-east-2": {"public": "us-east-2a", "private": "us-east-2b"},
    "us-west-1": {"public": "us-west-1a", "private": "us-west-1b"},
    "us-west-2": {"public": "us-west-2a", "private": "us-west-2b"},
}
