# Project metadata for Vantage CLI
name: "vantage-cli"
version: "0.1.0"
description: "CLI for authentication, profiles, clusters, apps & GraphQL against the Vantage Compute platform"
repository: "https://github.com/vantagecompute/vantage-cli"
documentation: "https://vantagecompute.github.io/vantage-cli"
license: "Apache 2.0"
python_version: ">=3.12"
updated: "2025-09-09"



# Key technologies
technologies:
  - "Python 3.12+"
  - "Typer CLI Framework"
  - "Rich Terminal UI"
  - "HTTPX Async Client"
  - "GraphQL"
  - "OIDC / OAuth2"
  - "Pytest"
  - "uv Package Manager"
  - "Pydantic-style Schemas"
  - "GitHub Actions CI"
  - "MicroK8s (app helper)"
  - "Multipass (app helper)"
  - "Juju (app helper)"

# Package features
features:
  - "Profile & token management"
  - "Cluster create/list/get/delete"
  - "Client secret retrieval"
  - "App deployment helpers"
  - "GraphQL query execution"
  - "Retry & metrics logging"
  - "JSON or Rich output"
  - "High test coverage"