"""Core module for defining constants across the app."""


# used when naming demo clusters. These lists must have a prime number as length
CLUSTER_ADJECTIVE_LIST = [
    "shady",
    "distant",
    "peaceful",
    "placid",
    "verdant",
    "calm",
    "misty",
    "sunny",
    "lush",
    "quiet",
    "hidden",
    "vibrant",
    "sparkling",
    "serene",
    "tranquil",
    "majestic",
    "mysterious",
    "scenic",
    "picturesque",
    "relaxing",
    "soothing",
    "breathtaking",
    "captivating",
    "charming",
    "enchanting",
    "idyllic",
    "panoramic",
    "pristine",
    "unspoiled",
    "whispering",
]
CLUSTER_NOUN_LIST = [
    "glen",
    "meadow",
    "river",
    "stream",
    "lake",
    "hill",
    "mountain",
    "trail",
    "path",
    "bluff",
    "creek",
    "plain",
    "valley",
    "forest",
    "woodland",
    "waterfall",
    "canyon",
    "oasis",
    "beach",
    "island",
    "desert",
    "plateau",
    "ridge",
    "summit",
    "cavern",
    "cove",
    "bay",
    "harbor",
    "lagoon",
    "estuary",
]
CLUSTER_ALL_POSSIBLE_NAMES = {
    f"demo-{adjective}-{noun}" for adjective in CLUSTER_ADJECTIVE_LIST for noun in CLUSTER_NOUN_LIST
}
