# Copyright (c) 2025 James Beedy.
# GitHub Pages configuration for Vantage CLI
title: Vantage CLI
description: A powerful Python CLI for interacting with the Vantage platform.
version: "0.1.3"

# Site settings
url: "https://vantagecompute.github.io"
baseurl: "/vantage-cli"
repository: "vantagecompute/vantage-cli"

# Logo and branding
show_downloads: true

# Author information
author:
  name: "James Beedy"
  email: "james@vantagecompute.ai"

# Social links
github_username: vantagecompute

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false
    block:
      line_numbers: false
    span:
      line_numbers: false
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"
